language: node_js
node_js: 10

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

stages:
  - 'Test'
  - name: 'Deploy'
    if: branch = master AND type = push

jobs:
  fail_fast: true
  include:
    - stage: 'Test'
      name: 'Conventional Commits'
      script: commitlint-travis
    - name: 'Fixed Dependencies'
      before_script: yarn global add codecov
      install: yarn install --non-interactive
      script: node_modules/.bin/nyc yarn test
      after_success: codecov
    - name: 'Floating Dependencies'

    - stage: 'Deploy'
      name: 'Publish to npm'
      install:
        - yarn install --non-interactive
      script: yarn semantic-release
